from enum import StrEnum


class ApplicationErrorCode(StrEnum):
    STANDARD_ERROR_USE_CASE_NOT_FOUND = "1-1"
    STANDARD_ERROR_USE_CASE_OUTPUT_NOT_HANDLER_INVALID_INPUT = "1-2"
    STANDARD_ERROR_USE_CASE_INPUT_INVALID_TYPE = "1-3"
    STANDARD_ERROR_USE_CASE_OUTPUT_HANDLER_INVALID_TYPE = "1-4"
